version: "3.8"
services:
  app:
    container_name: fcgi_app
    build: ./app/
    networks:
      app_net:
        ipv4_address: 172.29.0.7
    
  nginx:
    container_name: nginx_proxy
    build: ./proxy/
    networks:
      app_net:
        ipv4_address: 172.29.0.6
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.29.2.0/16"
